#!/bin/bash
echo "🔧 修复Next.js服务器错误"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "步骤1: 完全删除.next缓存..."
rm -rf .next
echo "✅ .next缓存已删除"
echo ""
echo "步骤2: 清理node_modules缓存..."
rm -rf node_modules/.cache
echo "✅ node_modules缓存已清理"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ 清理完成！"
echo ""
echo "⚠️  请手动完成以下步骤："
echo ""
echo "1️⃣  找到正在运行npm run dev的终端"
echo "2️⃣  按 Ctrl+C 停止服务器"
echo "3️⃣  运行: npm run dev"
echo "4️⃣  等待服务器完全启动（看到'ready'信息）"
echo "5️⃣  访问: http://localhost:3008/user/bindcompany"
echo "6️⃣  在浏览器按: Cmd/Ctrl + Shift + R 硬刷新"
echo ""
